---
title: "Topic Homework"
---

 

+ Assignment 1 
```{r, echo=FALSE, out.width = '800px', out.height = '400px', results='asis'}
cat('<embed src="./Assignments/STA13 HW1.pdf" 
    type="application/pdf" 
    width="100%" height="400px" />')
```
 
+ Assignment 2 
```{r, echo=FALSE, out.width = '800px', out.height = '400px', results='asis'}
cat('<embed src="./Assignments/STA13 HW2.pdf" 
    type="application/pdf" 
    width="100%" height="400px" />')
```

+ Assignment 3 
```{r, echo=FALSE, out.width = '800px', out.height = '400px', results='asis'}
cat('<embed src="./Assignments/STA13 HW3.pdf" 
    type="application/pdf" 
    width="100%" height="400px" />')
```

+ Assignment 4 
```{r, echo=FALSE, out.width = '800px', out.height = '400px', results='asis'}
cat('<embed src="./Assignments/STA13 HW4.pdf" 
    type="application/pdf" 
    width="100%" height="400px" />')
```

+ Assignment 5
```{r, echo=FALSE, out.width = '800px', out.height = '400px', results='asis'}
cat('<embed src="./Assignments/STA13 HW5.pdf" 
    type="application/pdf" 
    width="100%" height="400px" />')
```


+ Assignment 6 
```{r, echo=FALSE, out.width = '800px', out.height = '400px', results='asis'}
cat('<embed src="./Assignments/STA13 HW6.pdf" 
    type="application/pdf" 
    width="100%" height="400px" />')
```